# ...existing code...

from django.urls import path, include
# ...existing code...

urlpatterns = [
    # ...existing code...
    path('', include('home.urls')),  # Add home app URLs at root path
    # ...existing code...
]
