# Generated by Django 4.2.5 on 2025-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opord',
            fields=[
                ('xordernum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xdate', models.DateField(blank=True, null=True)),
                ('xcus', models.CharField(blank=True, max_length=50, null=True)),
                ('xstatusord', models.CharField(blank=True, max_length=20, null=True)),
                ('xdisc', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('xdtwotax', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('xsltype', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'opord',
                'managed': False,
            },
        ),
    ]
