# Generated by Django 4.2.5 on 2025-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_module_permissiongroup_usergroupmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
