# Generated by Django 4.2.5 on 2025-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_module_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
