# Generated by Django 4.2.7 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_business_address_business_city_business_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='zid',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
