# Generated by Django 4.2.7 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_business_zid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AlterField(
            model_name='business',
            name='zid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Business ID'),
        ),
    ]
