# Generated by Django 4.2.7 on 2025-11-03 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_business_id_alter_business_zid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_groups', models.TextField(help_text="Comma-separated permission group names (e.g., 'group-a,group-b,group-c')")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='authentication.business')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module')),
            ],
            options={
                'verbose_name': 'Business Module Access',
                'verbose_name_plural': 'Business Module Access',
                'unique_together': {('business', 'module')},
            },
        ),
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': 'Permission Group', 'verbose_name_plural': 'Permission Groups'},
        ),
        migrations.AlterModelOptions(
            name='usergroupmembership',
            options={'verbose_name': 'User Group Membership', 'verbose_name_plural': 'User Group Memberships'},
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 12, 32, 22, 714359, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.CharField(choices=[('view', 'View Only'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('full', 'Full Access (All Permissions)')], default='', help_text='Select the permission level for this group', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 12, 36, 18, 871993, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BusinessModuleGroupAccess',
        ),
    ]
