# Generated by Django 4.2.7 on 2025-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_businessmoduleaccess_alter_permissiongroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='permissions',
            field=models.TextField(blank=True, help_text='Comma-separated list of permissions (view, create, edit, delete)'),
        ),
    ]
